name: Deploy Gatsby Static Assets to S3 Bucket
env:
  owner: SharjeelSafdar
  repo: project13b-bookmarking-app-with-aws

# Controls when the action will run. Triggers the workflow on
# 1) push event for main branch
# 2) pull_request generated on main branch
# 3) It's triggered only by changes in relavent files in client/ directory
on:
  push:
    branch: [main]
    paths-ignore:
      - "README.md"
      - "backend/lib/backend-services-stack.ts"
      - "backend/test/backend-services-stack.test.ts"
      - "backend/.gitignore"
      - "backend/.nomignore"
      - "backend/.README.md"
      - "client/.gitignore"
      - "client/.README.md"
      - "client/.vscode/**"
      - "client/.prettierignore"
      - "client/.prettierrc"
      - "client/LICENSE"
      - ".github/workflows/deployBackendServicesStack.yml"
  pull_request:
    branch: [main]
    paths-ignore:
      - "README.md"
      - "backend/lib/backend-services-stack.ts"
      - "backend/test/backend-services-stack.test.ts"
      - "backend/.gitignore"
      - "backend/.nomignore"
      - "backend/.README.md"
      - "client/.gitignore"
      - "client/.README.md"
      - "client/.vscode/**"
      - "client/.prettierignore"
      - "client/.prettierrc"
      - "client/LICENSE"
      - ".github/workflows/deployBackendServicesStack.yml"

jobs:
  Build_Gatsby_Static_Assets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with: { node-version: "14.15.0" }

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: client

      - name: Build Gatsby App
        working-directory: client
        run: npm run build

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: backend

      - name: Build CDK App with TypeScript Compiler
        working-directory: backend
        run: npm run build

      # - name: Run tests with Jest
      #   working-directory: backend
      #   run: npm run test test/frontend-deploy-stack.test.ts

      - name: Deploy Frontend Deploy Stack to AWS CloudFormation
        uses: docker://kikemnzz/automate-cdk-github-action-kmzz:v1.0.0
        with:
          cdk_version: 1.109
          cdk_action: deploy
          cdk_stack: P13bFrontendDeployStack
          cdk_stack_directory: backend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
